/*RECETAS DE EJEMPLOS*/
export const recetasEjemplo = [
    {
        id: "1",
        orden: 1,
        titulo: "Fideos de arroz con tofu",
        descripcion: "Receta vegana con tofu firme y pimiento rojo",
        categoria: "vegana",
        dificultad: "Fácil",
        ingredientes: ["fideos de arroz", "tofu", "pimiento", "salsa de soja"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/fideos-tofu",
        porciones: "2",
        tipoCocina: "asiática",
        dieta: "Vegana",
        tipoPlato: "Principal",
        tiempo: "30 minutos",
        instrucciones:""
    },
    {
        id: "2",
        orden: 2,
        titulo: "Tacos de carne",
        descripcion: "Tacos tradicionales con carne sazonada y vegetales frescos",
        categoria: "mexicana",
        dificultad: "Media",
        ingredientes: ["tortillas", "carne molida", "lechuga", "tomate", "queso"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/tacos-carne",
        porciones: "4",
        tipoCocina: "mexicana",
        dieta: "Omnívora",
        tipoPlato: "Principal",
        tiempo: "1 hora y 30 minutos",
        instrucciones:""
    },
    {
        id: "3",
        orden: 3,
        titulo: "Ensalada César",
        descripcion: "Ensalada clásica con aderezo César y crutones",
        categoria: "ensalada",
        dificultad: "Fácil",
        ingredientes: ["lechuga romana", "crutones", "queso parmesano", "aderezo César"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/ensalada-cesar",
        porciones: "2",
        tipoCocina: "internacional",
        dieta: "Vegetariana",
        tipoPlato: "Entrada",
        tiempo: "15 minutos",
        instrucciones:""
    },
    {
        id: "4",
        orden: 4,
        titulo: "Sopa de lentejas",
        descripcion: "Sopa nutritiva con lentejas, zanahoria y apio",
        categoria: "sopa",
        dificultad: "Fácil",
        ingredientes: ["lentejas", "zanahoria", "apio", "cebolla", "ajo"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/sopa-lentejas",
        porciones: "4",
        tipoCocina: "internacional",
        dieta: "Vegetariana",
        tipoPlato: "Sopa",
        tiempo: "45 minutos",
        instrucciones:""
    },
    {
        id: "5",
        orden: 5,
        titulo: "Pizza margarita",
        descripcion: "Pizza italiana con salsa de tomate, mozzarella y albahaca",
        categoria: "italiana",
        dificultad: "Media",
        ingredientes: ["masa de pizza", "salsa de tomate", "mozzarella", "albahaca"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/pizza-margarita",
        porciones: "2",
        tipoCocina: "italiana",
        dieta: "Vegetariana",
        tipoPlato: "Principal",
        tiempo: "1 hora",
        instrucciones:""
    },
    {
        id: "6",
        orden: 6,
        titulo: "Curry de garbanzos",
        descripcion: "Curry vegano con garbanzos y leche de coco",
        categoria: "india",
        dificultad: "Media",
        ingredientes: ["garbanzos", "leche de coco", "curry", "cebolla", "ajo"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/curry-garbanzos",
        porciones: "3",
        tipoCocina: "india",
        dieta: "Vegana",
        tipoPlato: "Principal",
        tiempo: "40 minutos",
        instrucciones:""
    },
    {
        id: "7",
        orden: 7,
        titulo: "Panqueques integrales",
        descripcion: "Panqueques saludables con harina integral y miel",
        categoria: "desayuno",
        dificultad: "Fácil",
        ingredientes: ["harina integral", "huevo", "leche", "miel"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/panqueques-integrales",
        porciones: "4",
        tipoCocina: "saludable",
        dieta: "Vegetariana",
        tipoPlato: "Postre",
        tiempo: "20 minutos",
        instrucciones:""
    },
    {
        id: "8",
        orden: 8,
        titulo: "Bowl de quinoa",
        descripcion: "Bowl nutritivo con quinoa, aguacate y vegetales",
        categoria: "saludable",
        dificultad: "Fácil",
        ingredientes: ["quinoa", "aguacate", "zanahoria", "pepino", "sésamo"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/bowl-quinoa",
        porciones: "2",
        tipoCocina: "saludable",
        dieta: "Vegana",
        tipoPlato: "Principal",
        tiempo: "25 minutos",
        instrucciones:""
    },
    {
        id: "9",
        orden: 9,
        titulo: "Lasaña de verduras",
        descripcion: "Lasaña al horno con berenjena, calabacín y salsa bechamel",
        categoria: "italiana",
        dificultad: "Alta",
        ingredientes: ["láminas de lasaña", "berenjena", "calabacín", "salsa bechamel"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/lasana-verduras",
        porciones: "4",
        tipoCocina: "italiana",
        dieta: "Vegetariana",
        tipoPlato: "Principal",
        tiempo: "1 hora y 15 minutos",
        instrucciones:""
    },
    {
        id: "10",
        orden: 10,
        titulo: "Smoothie de frutos rojos",
        descripcion: "Bebida refrescante con frutillas, arándanos y yogur",
        categoria: "bebida",
        dificultad: "Fácil",
        ingredientes: ["frutillas", "arándanos", "yogur", "miel"],
        imagen_url: "",
        url: "https://recetas.ejemplo.com/smoothie-frutos-rojos",
        porciones: "2",
        tipoCocina: "saludable",
        dieta: "Vegetariana",
        tipoPlato: "Bebida",
        tiempo: "10 minutos",
        instrucciones:""
    }
];
